### ISSUE TITLE
hello...

### ISSUE THREAD

**Issue by travis-r6s** [unodelostrece/unodelostrece.github.io#1]
my apologies - i cant see any way of contacting you.

Just wondering how far you had got with this project? I have been looking to do exactly the same thing with jamstash and electron, but am relatively new to electron and still finding my way around it, and would be glad of any pointers, or to help in this.

thanks,

**Comment by rafacapa** [comment]
Hi Travis. The fact is I didn't work too mucho on this. I had the plan to
dedicate some time to this, but ater a while I had to dismiss the idea due
to my lack of time :(
This pretended to be my fisrt electron project, so I'm afraid I won't be
able to help you.

Thanks and goog luck!

2016-10-27 16:36 GMT+02:00 Travis Reynolds notifications@github.com:
